// Generated by CoffeeScript 1.6.3
(function() {
  var thru;

  thru = require('through');

  module.exports = (function() {
    var end, start, write;
    start = null;
    write = function(data) {
      var d;
      if (data) {
        data = JSON.parse(data);
        if (data.id) {
          if (!start) {
            start = data.timestamp;
          }
          d = {
            id: data.id,
            time: data.timestamp - start,
            hands: data.hands
          };
          return this.queue(JSON.stringify(d) + '\n');
        }
      }
    };
    end = function() {
      return this.queue(null);
    };
    return thru(write, end);
  })();

}).call(this);
