// Generated by CoffeeScript 1.6.3
(function() {
  var createWriteStream, readline, ws;

  createWriteStream = require('fs').createWriteStream;

  readline = require('readline');

  ws = require('websocket-stream');

  module.exports = function(path) {
    var prompt;
    prompt = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    return prompt.question('Hit return to start recording ... ', function() {
      var filename, stream, toFile;
      stream = ws('ws://localhost:6437');
      filename = process.argv[2] || 'sample.ldj';
      toFile = createWriteStream(filename);
      stream.pipe(toFile);
      return prompt.question('Hit return again to stop recording ... ', function() {
        stream.end();
        prompt.close();
        console.log("Sample written to " + filename);
        return process.exit(0);
      });
    });
  };

}).call(this);
