// Generated by CoffeeScript 1.6.3
(function() {
  var createWriteStream, filter, readline, ws;

  createWriteStream = require('fs').createWriteStream;

  readline = require('readline');

  ws = require('websocket-stream');

  filter = require('filter/hands');

  module.exports = function(path) {
    var prompt;
    prompt = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    return prompt.question('Hit return to start recording ... ', function() {
      var stream, toFile;
      stream = ws('ws://localhost:6437');
      toFile = createWriteStream(process.argv[2] || 'sample.json.lsv');
      stream.pipe(filter).pipe(toFile);
      return prompt.question('Hit return again to stop recording ... ', function() {
        stream.end();
        return prompt.close();
      });
    });
  };

}).call(this);
